AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Style/Semicolon:
  AllowAsExpressionSeparator: true

Metrics/MethodLength:
  Max: 15

Layout/LineLength:
  Max: 120
